var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/services/route.js")
R.c("server/chunks/[root-of-the-server]__47f4d86d._.js")
R.c("server/chunks/src_lib_dashboard-fixtures_ts_5c4763c1._.js")
R.c("server/chunks/src_lib_dashboard-data_ts_e8100774._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/_next-internal_server_app_api_services_route_actions_0dc2c8f6.js")
R.m(77746)
module.exports=R.m(77746).exports
