// ============================================================
// Ren'Py script generation utilities
// ============================================================

import {
  CharacterDNA,
  RenpyCharacterDef,
  LayeredImageConfig,
  ATLTransform,
  ScreenDef,
  ChoiceOption,
  HSceneConfig,
  IntensityLevel,
  CorruptionStage,
  EndingConfig,
  AffinityConfig,
  PhoneMessage,
} from "./types.js";

// ── Indentation helpers ────────────────────────────────────────

export function indent(lines: string[], spaces: number = 4): string {
  const pad = " ".repeat(spaces);
  return lines.map((l) => (l.trim() === "" ? "" : pad + l)).join("\n");
}

export function block(...lines: string[]): string {
  return lines.join("\n");
}

// ── File header ────────────────────────────────────────────────

export function fileHeader(description: string): string {
  return [
    `# ${description}`,
    `# Generated by mcp-renpy — EoBQ SoulForge Engine`,
    `# Do not edit labels prefixed with ## GENERATED ##`,
    ``,
  ].join("\n");
}

// ── Character definitions ──────────────────────────────────────

export function generateCharacterDef(def: RenpyCharacterDef): string {
  const parts: string[] = [`define ${def.id} = Character(`];
  const args: string[] = [`    "${def.name}"`];

  if (def.color) args.push(`    color="${def.color}"`);
  if (def.voice_tag) args.push(`    voice_tag="${def.voice_tag}"`);
  if (def.what_font) args.push(`    what_font="${def.what_font}"`);
  if (def.what_size) args.push(`    what_size=${def.what_size}`);
  if (def.image) args.push(`    image="${def.image}"`);
  if (def.callback) args.push(`    callback=${def.callback}`);

  parts.push(args.join(",\n"));
  parts.push(`)"`);
  // Reconstruct properly
  const inner = args.map((a) => `    ${a.trim()}`).join(",\n");
  return `define ${def.id} = Character(\n${inner}\n)`;
}

export function generateCharacterFromDNA(dna: CharacterDNA): string {
  const varName = dna.name.toLowerCase().replace(/\s+/g, "_");
  const lines: string[] = [
    `## GENERATED ## Character: ${dna.name} — Archetype: ${dna.archetype}`,
    `define ${varName} = Character(`,
    `    "${dna.name}",`,
    `    color="${dna.color_hex}",`,
    `    voice_tag="${varName}",`,
    `    image="${varName}",`,
    `)`,
    ``,
    `## DNA Profile: corruption_vector=${dna.corruption_vector} | affinity=${dna.affinity_type}`,
    `## Kink profile: ${dna.kink_profile.join(", ")}`,
  ];
  return lines.join("\n");
}

// ── Layered image ──────────────────────────────────────────────

export function generateLayeredImage(config: LayeredImageConfig): string {
  const lines: string[] = [`layered_image ${config.name}:`];
  if (config.base) {
    lines.push(`    always:`);
    lines.push(`        "${config.base}"`);
  }
  for (const attr of config.attributes) {
    lines.push(`    group ${attr.group}:`);
    if (attr.default) lines.push(`        default "${attr.default}"`);
    for (const val of attr.values) {
      lines.push(`        attribute ${val}:`);
      lines.push(`            "${config.name}/${attr.group}/${val}"`);
    }
  }
  return lines.join("\n");
}

// ── Labels & dialogue ──────────────────────────────────────────

export function generateLabel(name: string, body: string[]): string {
  return [`label ${name}:`, ...body.map((l) => `    ${l}`), ``].join("\n");
}

export function generateDialogue(
  speaker: string,
  text: string,
  tag?: string
): string {
  if (tag) return `${speaker} ${tag} "${text}"`;
  return `${speaker} "${text}"`;
}

export function generateNarration(text: string): string {
  return `"${text}"`;
}

export function generateChoiceMenu(
  prompt: string,
  options: ChoiceOption[]
): string {
  const lines: string[] = [`menu:`];
  if (prompt) lines.push(`    "${prompt}"`);
  lines.push(``);
  for (const opt of options) {
    const cond = opt.condition ? ` if ${opt.condition}` : "";
    lines.push(`    "${opt.text}"${cond}:`);
    if (opt.affinity_delta) {
      for (const [char, delta] of Object.entries(opt.affinity_delta)) {
        const op = delta >= 0 ? `+= ${delta}` : `-= ${Math.abs(delta)}`;
        lines.push(`        $ ${char}_affinity ${op}`);
      }
    }
    if (opt.jump) lines.push(`        jump ${opt.jump}`);
    else lines.push(`        pass`);
    lines.push(``);
  }
  return lines.join("\n");
}

// ── Scene building ─────────────────────────────────────────────

export function generateScene(
  background: string,
  transition?: string
): string {
  const t = transition ? ` with ${transition}` : "";
  return `scene ${background}${t}`;
}

export function generateShow(
  image: string,
  at?: string,
  transition?: string
): string {
  const atPart = at ? ` at ${at}` : "";
  const withPart = transition ? ` with ${transition}` : "";
  return `show ${image}${atPart}${withPart}`;
}

export function generateHide(image: string, transition?: string): string {
  const withPart = transition ? ` with ${transition}` : "";
  return `hide ${image}${withPart}`;
}

export function generatePlayMusic(
  file: string,
  fadeout?: number,
  fadein?: number
): string {
  const parts: string[] = [`play music "${file}"`];
  if (fadeout) parts.push(`fadeout ${fadeout}`);
  if (fadein) parts.push(`fadein ${fadein}`);
  return parts.join(" ");
}

export function generatePlaySound(file: string, channel?: string): string {
  const ch = channel ? `channel "${channel}" ` : "";
  return `play sound ${ch}"${file}"`;
}

export function generateTransition(name: string): string {
  return `with ${name}`;
}

// ── ATL transforms ─────────────────────────────────────────────

export function generateATLTransform(t: ATLTransform): string {
  return [`transform ${t.name}:`, indent(t.body.split("\n"), 4)].join("\n");
}

export function generateATLAnimation(
  name: string,
  frames: { image: string; delay: number }[]
): string {
  const lines: string[] = [`transform ${name}:`];
  for (const frame of frames) {
    lines.push(`    "${frame.image}"`);
    lines.push(`    pause ${frame.delay}`);
  }
  return lines.join("\n");
}

// ── Screens ────────────────────────────────────────────────────

export function generateScreen(def: ScreenDef): string {
  const paramStr = def.params ? `(${def.params.join(", ")})` : "";
  return [
    `screen ${def.name}${paramStr}:`,
    indent(def.body.split("\n"), 4),
  ].join("\n");
}

// ── Variables & defaults ───────────────────────────────────────

export function generateDefault(name: string, value: string): string {
  return `default ${name} = ${value}`;
}

export function generateDefine(name: string, value: string): string {
  return `define ${name} = ${value}`;
}

export function generateConditionBlock(
  conditions: { condition: string; body: string[] }[],
  else_body?: string[]
): string {
  const lines: string[] = [];
  conditions.forEach((c, i) => {
    const keyword = i === 0 ? "if" : "elif";
    lines.push(`${keyword} ${c.condition}:`);
    lines.push(...c.body.map((l) => `    ${l}`));
  });
  if (else_body) {
    lines.push(`else:`);
    lines.push(...else_body.map((l) => `    ${l}`));
  }
  return lines.join("\n");
}

export function generatePythonBlock(code: string): string {
  return [`python:`, indent(code.split("\n"), 4)].join("\n");
}

// ── Affinity system ────────────────────────────────────────────

export function generateAffinityDefaults(cfg: AffinityConfig): string {
  return [
    `## Affinity: ${cfg.character_id}`,
    `default ${cfg.variable_name} = 0`,
    `define ${cfg.character_id}_affinity_thresholds = {`,
    `    "low": ${cfg.thresholds.low},`,
    `    "medium": ${cfg.thresholds.medium},`,
    `    "high": ${cfg.thresholds.high},`,
    `    "max": ${cfg.thresholds.max},`,
    `}`,
    `define ${cfg.character_id}_route_unlock = ${cfg.route_unlock_threshold}`,
  ].join("\n");
}

export function generateAffinityCheck(
  variable: string,
  character_id: string
): string {
  return [
    `## Affinity check helper for ${character_id}`,
    `label affinity_check_${character_id}:`,
    `    if ${variable} >= ${character_id}_route_unlock:`,
    `        $ persistent.${character_id}_route_unlocked = True`,
    `    return`,
  ].join("\n");
}

// ── H-scene generation ─────────────────────────────────────────

const INTENSITY_TAGS: Record<IntensityLevel, string> = {
  soft: "## [SOFT]",
  medium: "## [MEDIUM]",
  explicit: "## [EXPLICIT]",
  extreme: "## [EXTREME]",
};

export function generateHScene(cfg: HSceneConfig): string {
  const charVar = cfg.character_id;
  const tag = INTENSITY_TAGS[cfg.intensity];
  const lines: string[] = [
    `${tag} H-Scene: ${cfg.character_id} | Stage ${cfg.corruption_stage}`,
    `## DNA: ${cfg.dna.archetype} | vector: ${cfg.dna.corruption_vector}`,
    ``,
    `label ${cfg.label}:`,
  ];

  if (cfg.unlock_condition) {
    lines.push(`    ## Unlock condition: ${cfg.unlock_condition}`);
  }

  for (const act of cfg.acts) {
    lines.push(`    ## Act: ${act.id} — ${act.description}`);
    if (act.has_cg && cfg.cg_prefix) {
      lines.push(`    show ${cfg.cg_prefix}_${act.id} with dissolve`);
    }
    for (let i = 0; i < act.dialogue_count; i++) {
      lines.push(
        `    ${charVar} "## DIALOGUE ${i + 1}: [${cfg.dna.voice_style}] placeholder"`
      );
    }
    lines.push(``);
  }

  lines.push(`    return`);
  return lines.join("\n");
}

// ── Corruption arc ─────────────────────────────────────────────

export function generateCorruptionArc(
  queen_id: string,
  stages: CorruptionStage[]
): string {
  const lines: string[] = [
    `## Corruption arc: ${queen_id}`,
    `default ${queen_id}_corruption = 0`,
    ``,
  ];

  for (const stage of stages) {
    lines.push(`## Stage ${stage.stage}: ${stage.label}`);
    lines.push(`label ${queen_id}_corruption_${stage.stage}:`);
    lines.push(
      `    ## Trigger: ${stage.trigger_condition} | Type: ${stage.scene_type}`
    );
    lines.push(`    ## ${stage.description}`);
    lines.push(
      `    ## Intensity: ${stage.intensity} — fill with generated content`
    );
    lines.push(`    $ ${queen_id}_corruption = ${stage.stage}`);
    lines.push(`    return`);
    lines.push(``);
  }

  return lines.join("\n");
}

// ── Endings ────────────────────────────────────────────────────

export function generateEnding(cfg: EndingConfig): string {
  const lines: string[] = [
    `## Ending: ${cfg.type.toUpperCase()} — "${cfg.title}"`,
    `label ${cfg.label}:`,
    `    ## Conditions: ${cfg.conditions.join(" AND ")}`,
    `    ## ${cfg.description}`,
  ];

  if (cfg.music) lines.push(`    play music "${cfg.music}" fadein 2.0`);

  lines.push(`    scene black with dissolve`);

  if (cfg.cg) {
    lines.push(`    pause 1.0`);
    lines.push(`    show ${cfg.cg} with dissolve`);
  }

  lines.push(`    "## ENDING NARRATION PLACEHOLDER"`);
  lines.push(``);
  lines.push(`    ## Unlock achievement`);
  lines.push(`    $ renpy.achievement.grant("ending_${cfg.type}")`);
  lines.push(`    jump _return`);

  return lines.join("\n");
}

// ── Phone messages ─────────────────────────────────────────────

export function generatePhoneMessages(msgs: PhoneMessage[]): string {
  const lines: string[] = [`## Phone message sequence`];

  for (const msg of msgs) {
    lines.push(`label phone_${msg.sender}_${msg.timestamp_label}:`);
    lines.push(`    ## Obsession level: ${msg.obsession_level}/5`);
    lines.push(`    call screen phone_overlay`);
    for (const text of msg.messages) {
      lines.push(`    ## Message: "${text}"`);
    }
    if (msg.attachment) {
      lines.push(`    ## Attachment: ${msg.attachment}`);
    }
    lines.push(`    return`);
    lines.push(``);
  }

  return lines.join("\n");
}

// ── Gallery ────────────────────────────────────────────────────

export function generateGalleryEntry(
  id: string,
  name: string,
  image: string,
  unlock_condition: string,
  thumbnail?: string
): string {
  return [
    `## Gallery entry: ${name}`,
    `python early:`,
    `    gallery.button("${id}")`,
    `    gallery.unlock_condition("${unlock_condition}")`,
    `    gallery.image("${image}")`,
    thumbnail ? `    gallery.thumbnail("${thumbnail}")` : null,
  ]
    .filter(Boolean)
    .join("\n");
}

// ── Achievement ────────────────────────────────────────────────

export function generateAchievement(
  id: string,
  name: string,
  description: string,
  icon?: string,
  points?: number
): string {
  const lines = [
    `define achievement.${id} = Achievement(`,
    `    name="${name}",`,
    `    description="${description}",`,
  ];
  if (icon) lines.push(`    icon="${icon}",`);
  if (points !== undefined) lines.push(`    points=${points},`);
  lines.push(`)`);
  return lines.join("\n");
}

// ── Project structure ──────────────────────────────────────────

export function generateProjectOptions(config: {
  name: string;
  build_name: string;
  version: string;
  developer: string;
  copyright: string;
}): string {
  return [
    `define config.name = "${config.name}"`,
    `define build.name = "${config.build_name}"`,
    `define config.version = "${config.version}"`,
    `define config.developer = "${config.developer}"`,
    `define config.copyright = "${config.copyright}"`,
  ].join("\n");
}

// ── Flowchart extraction ───────────────────────────────────────

export interface FlowNode {
  label: string;
  jumps: string[];
  calls: string[];
  menus: { prompt: string; options: string[] }[];
}

export function parseFlowchart(script: string): FlowNode[] {
  const nodes: FlowNode[] = [];
  const labelRegex = /^label\s+(\w+)\s*:/gm;
  const jumpRegex = /^\s+jump\s+(\w+)/gm;
  const callRegex = /^\s+call\s+(\w+)/gm;
  const menuRegex = /^\s+menu\s*:/gm;

  let labelMatch: RegExpExecArray | null;
  const labels: { name: string; start: number }[] = [];

  while ((labelMatch = labelRegex.exec(script)) !== null) {
    labels.push({ name: labelMatch[1], start: labelMatch.index });
  }

  for (let i = 0; i < labels.length; i++) {
    const label = labels[i];
    const end = i + 1 < labels.length ? labels[i + 1].start : script.length;
    const segment = script.slice(label.start, end);

    const jumps: string[] = [];
    let jm: RegExpExecArray | null;
    const jr = /jump\s+(\w+)/g;
    while ((jm = jr.exec(segment)) !== null) jumps.push(jm[1]);

    const calls: string[] = [];
    let cm: RegExpExecArray | null;
    const cr = /call\s+(\w+)/g;
    while ((cm = cr.exec(segment)) !== null) calls.push(cm[1]);

    nodes.push({ label: label.name, jumps, calls, menus: [] });
  }

  return nodes;
}

export function renderFlowchartDot(nodes: FlowNode[]): string {
  const lines: string[] = [
    `digraph EoBQ {`,
    `    rankdir=TB;`,
    `    node [shape=box, fontname="Helvetica"];`,
    ``,
  ];

  for (const node of nodes) {
    lines.push(`    "${node.label}" [label="${node.label}"];`);
    for (const j of node.jumps) {
      lines.push(`    "${node.label}" -> "${j}" [style=solid];`);
    }
    for (const c of node.calls) {
      lines.push(`    "${node.label}" -> "${c}" [style=dashed];`);
    }
  }

  lines.push(`}`);
  return lines.join("\n");
}

// ── Utility: extract strings ───────────────────────────────────

export function extractTranslatableStrings(script: string): string[] {
  const strings: string[] = [];
  // Match quoted strings not preceded by # or define/default
  const regex = /(?<!#.*)"([^"\\]|\\.)+"/g;
  let m: RegExpExecArray | null;
  while ((m = regex.exec(script)) !== null) {
    strings.push(m[0]);
  }
  return [...new Set(strings)];
}

// ── Utility: merge scripts ─────────────────────────────────────

export function mergeScripts(a: string, b: string): string {
  return [a.trimEnd(), ``, `## --- Merged from second file ---`, ``, b.trimStart()].join("\n");
}

// ── Utility: validate basic syntax ────────────────────────────

export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

export function validateScript(script: string): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const lines = script.split("\n");

  // Check for unclosed quotes
  lines.forEach((line, i) => {
    const ln = i + 1;
    const stripped = line.replace(/##.*/g, "");
    const quotes = (stripped.match(/"/g) || []).length;
    if (quotes % 2 !== 0) {
      errors.push(`Line ${ln}: Unclosed string literal`);
    }
  });

  // Check label naming
  const labelRegex = /^label\s+([^\s:]+)\s*:/gm;
  const seen = new Set<string>();
  let m: RegExpExecArray | null;
  while ((m = labelRegex.exec(script)) !== null) {
    if (seen.has(m[1])) {
      errors.push(`Duplicate label: ${m[1]}`);
    }
    seen.add(m[1]);
  }

  // Check jumps resolve
  const jumpRegex = /jump\s+(\w+)/g;
  while ((m = jumpRegex.exec(script)) !== null) {
    if (!seen.has(m[1]) && m[1] !== "_return") {
      warnings.push(`Jump to undefined label: ${m[1]}`);
    }
  }

  return { valid: errors.length === 0, errors, warnings };
}
