var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/home/overview/route.js")
R.c("server/chunks/[root-of-the-server]__f892ed6c._.js")
R.c("server/chunks/src_lib_dashboard-data_ts_e8100774._.js")
R.c("server/chunks/src_lib_subpage-data_ts_8c676c18._.js")
R.c("server/chunks/src_lib_dashboard-fixtures_ts_5c4763c1._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_home_overview_route_actions_abc7531a.js")
R.m(57227)
module.exports=R.m(57227).exports
