// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/activity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activity">> = Specific
  const handler = {} as typeof import("../../src/app/activity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../src/app/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../src/app/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/conversations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/conversations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gallery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gallery">> = Specific
  const handler = {} as typeof import("../../src/app/gallery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/goals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/goals">> = Specific
  const handler = {} as typeof import("../../src/app/goals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/gpu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gpu">> = Specific
  const handler = {} as typeof import("../../src/app/gpu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/home/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/home">> = Specific
  const handler = {} as typeof import("../../src/app/home/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/insights/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/insights">> = Specific
  const handler = {} as typeof import("../../src/app/insights/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/learning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/learning">> = Specific
  const handler = {} as typeof import("../../src/app/learning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/media">> = Specific
  const handler = {} as typeof import("../../src/app/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitoring/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/monitoring/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/more/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/more">> = Specific
  const handler = {} as typeof import("../../src/app/more/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/offline">> = Specific
  const handler = {} as typeof import("../../src/app/offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/outputs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/outputs">> = Specific
  const handler = {} as typeof import("../../src/app/outputs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/personal-data/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personal-data">> = Specific
  const handler = {} as typeof import("../../src/app/personal-data/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/preferences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/preferences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../src/app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/services">> = Specific
  const handler = {} as typeof import("../../src/app/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tasks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/tasks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terminal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terminal">> = Specific
  const handler = {} as typeof import("../../src/app/terminal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workplanner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workplanner">> = Specific
  const handler = {} as typeof import("../../src/app/workplanner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/workspace/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/workspace">> = Specific
  const handler = {} as typeof import("../../src/app/workspace/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activity/operator-stream/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity/operator-stream">> = Specific
  const handler = {} as typeof import("../../src/app/api/activity/operator-stream/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/activity/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/activity">> = Specific
  const handler = {} as typeof import("../../src/app/api/activity/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../src/app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/api/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/autonomy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/autonomy">> = Specific
  const handler = {} as typeof import("../../src/app/api/autonomy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comfyui/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comfyui/generate">> = Specific
  const handler = {} as typeof import("../../src/app/api/comfyui/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comfyui/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comfyui/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/comfyui/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comfyui/image/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comfyui/image/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/comfyui/image/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comfyui/queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comfyui/queue">> = Specific
  const handler = {} as typeof import("../../src/app/api/comfyui/queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/comfyui/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/comfyui/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/comfyui/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/consolidation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consolidation">> = Specific
  const handler = {} as typeof import("../../src/app/api/consolidation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/consolidation/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/consolidation/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/consolidation/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/context/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/context/preview">> = Specific
  const handler = {} as typeof import("../../src/app/api/context/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conversations">> = Specific
  const handler = {} as typeof import("../../src/app/api/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/implicit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback/implicit">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/implicit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/feedback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feedback">> = Specific
  const handler = {} as typeof import("../../src/app/api/feedback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gallery/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gallery/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/gallery/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/cockpit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/cockpit">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/cockpit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/heartbeat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/heartbeat">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/heartbeat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/operations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/operations">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/operations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/operator-tests/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/operator-tests">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/operator-tests/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/pause/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/pause">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/pause/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/presence">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/release-tier/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/release-tier">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/release-tier/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/resume/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/resume">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/resume/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/governor/tool-permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/governor/tool-permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/governor/tool-permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gpu/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gpu/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/gpu/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/gpu/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gpu">> = Specific
  const handler = {} as typeof import("../../src/app/api/gpu/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/home/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/home/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/insights/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/insights/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/insights/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/intelligence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/intelligence">> = Specific
  const handler = {} as typeof import("../../src/app/api/intelligence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learning/benchmarks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/benchmarks">> = Specific
  const handler = {} as typeof import("../../src/app/api/learning/benchmarks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learning/improvement/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/improvement">> = Specific
  const handler = {} as typeof import("../../src/app/api/learning/improvement/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/learning/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/learning/metrics">> = Specific
  const handler = {} as typeof import("../../src/app/api/learning/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media">> = Specific
  const handler = {} as typeof import("../../src/app/api/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory">> = Specific
  const handler = {} as typeof import("../../src/app/api/memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/promotions/[promotionId]/advance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/promotions/[promotionId]/advance">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/promotions/[promotionId]/advance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/promotions/[promotionId]/hold/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/promotions/[promotionId]/hold">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/promotions/[promotionId]/hold/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/promotions/[promotionId]/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/promotions/[promotionId]/rollback">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/promotions/[promotionId]/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/promotions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/promotions">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/promotions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/retirements/[retirementId]/advance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/retirements/[retirementId]/advance">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/retirements/[retirementId]/advance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/retirements/[retirementId]/hold/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/retirements/[retirementId]/hold">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/retirements/[retirementId]/hold/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/retirements/[retirementId]/rollback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/retirements/[retirementId]/rollback">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/retirements/[retirementId]/rollback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/retirements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance/retirements">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/retirements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/governance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/governance">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/governance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/proving-ground/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models/proving-ground">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/proving-ground/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/models/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/models">> = Specific
  const handler = {} as typeof import("../../src/app/api/models/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/api/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/notification-budget/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notification-budget">> = Specific
  const handler = {} as typeof import("../../src/app/api/notification-budget/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outputs/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outputs/[...path]">> = Specific
  const handler = {} as typeof import("../../src/app/api/outputs/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/outputs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/outputs">> = Specific
  const handler = {} as typeof import("../../src/app/api/outputs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/overview">> = Specific
  const handler = {} as typeof import("../../src/app/api/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/personal-data/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personal-data/search">> = Specific
  const handler = {} as typeof import("../../src/app/api/personal-data/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/personal-data/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/personal-data/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/personal-data/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/preferences">> = Specific
  const handler = {} as typeof import("../../src/app/api/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../src/app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/send">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/push/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/push/subscribe">> = Specific
  const handler = {} as typeof import("../../src/app/api/push/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/jobs/[jobId]/execute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/jobs/[jobId]/execute">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/jobs/[jobId]/execute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/research/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/research/jobs">> = Specific
  const handler = {} as typeof import("../../src/app/api/research/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/review/judges/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/judges">> = Specific
  const handler = {} as typeof import("../../src/app/api/review/judges/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/routing/classify/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/routing/classify">> = Specific
  const handler = {} as typeof import("../../src/app/api/routing/classify/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/scheduling/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scheduling/status">> = Specific
  const handler = {} as typeof import("../../src/app/api/scheduling/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services/history">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/services/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/services">> = Specific
  const handler = {} as typeof import("../../src/app/api/services/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/skills/[skillId]/execution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skills/[skillId]/execution">> = Specific
  const handler = {} as typeof import("../../src/app/api/skills/[skillId]/execution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/skills/[skillId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skills/[skillId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/skills/[skillId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/skills/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skills">> = Specific
  const handler = {} as typeof import("../../src/app/api/skills/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/skills/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skills/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/skills/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/skills/top/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/skills/top">> = Specific
  const handler = {} as typeof import("../../src/app/api/skills/top/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/stash/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stash/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/stash/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/adopt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]/adopt">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/adopt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/adoption/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]/adoption">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/adoption/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/artifacts/[artifactName]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]/artifacts/[artifactName]">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/artifacts/[artifactName]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/artifacts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]/artifacts">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/artifacts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]/review">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/[executionId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution/[executionId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/[executionId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/execution/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/execution">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/execution/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/handoffs/[handoffId]/outcome/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/handoffs/[handoffId]/outcome">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/handoffs/[handoffId]/outcome/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/handoffs/[handoffId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/handoffs/[handoffId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/handoffs/[handoffId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/handoffs/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/handoffs/events">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/handoffs/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/handoffs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/handoffs">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/handoffs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/leases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/leases">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/leases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/policy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/policy">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/policy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/providers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/providers">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/providers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/quotas/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/quotas">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/quotas/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/routing-log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/routing-log">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/routing-log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/subscriptions/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/subscriptions/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/subscriptions/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/system-map/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/system-map">> = Specific
  const handler = {} as typeof import("../../src/app/api/system-map/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tts">> = Specific
  const handler = {} as typeof import("../../src/app/api/tts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/conventions/[conventionId]/confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/conventions/[conventionId]/confirm">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/conventions/[conventionId]/confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/conventions/[conventionId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/conventions/[conventionId]/reject">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/conventions/[conventionId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/goals/[goalId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/goals/[goalId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/goals/[goalId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/goals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/goals">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/goals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/notifications/[notificationId]/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/notifications/[notificationId]/resolve">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/notifications/[notificationId]/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/plan">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/redirect/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/redirect">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/redirect/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/runs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/runs">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/runs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/scheduled/[jobId]/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/scheduled/[jobId]/run">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/scheduled/[jobId]/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/scheduled">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/tasks/[taskId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/tasks/[taskId]/approve">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/tasks/[taskId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/tasks/[taskId]/cancel/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/tasks/[taskId]/cancel">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/tasks/[taskId]/cancel/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/tasks">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/workforce/workspace/[itemId]/endorse/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workforce/workspace/[itemId]/endorse">> = Specific
  const handler = {} as typeof import("../../src/app/api/workforce/workspace/[itemId]/endorse/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
