all:
  children:
    nodes:
      hosts:
        core:
          ansible_host: 192.168.1.244
          hostname: core
          node_role: inference
        interface:
          ansible_host: 192.168.1.225
          hostname: interface
          node_role: creative
    vault:
      hosts:
        vault:
          ansible_host: 192.168.1.203
          ansible_user: root
          ansible_ssh_pass: "{{ vault_ssh_password }}"
          hostname: Unraid
