var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/overview/route.js")
R.c("server/chunks/[root-of-the-server]__4e00dd14._.js")
R.c("server/chunks/src_lib_dashboard-fixtures_ts_5c4763c1._.js")
R.c("server/chunks/src_lib_dashboard-data_ts_e8100774._.js")
R.c("server/chunks/node_modules_next_1402a1da._.js")
R.c("server/chunks/node_modules_zod_v4_classic_external_fa90cebf.js")
R.c("server/chunks/[root-of-the-server]__8f5ebbc3._.js")
R.c("server/chunks/_next-internal_server_app_api_overview_route_actions_40f42359.js")
R.m(77621)
module.exports=R.m(77621).exports
