import type {
  AgentsSnapshot,
  GpuHistoryResponse,
  GpuSnapshotResponse,
  ModelsSnapshot,
  OverviewSnapshot,
  ServicesHistorySnapshot,
  ServicesSnapshot,
  WorkforceSnapshot,
} from "@/lib/contracts";

const FIXTURE_BASE_TIME = "2026-03-09T15:00:00.000Z";

function cloneFixture<T>(value: T): T {
  return structuredClone(value);
}

function isoMinutesBefore(base: string, minutesBefore: number) {
  return new Date(new Date(base).getTime() - minutesBefore * 60_000).toISOString();
}

function isoMinutesAfter(base: string, minutesAfter: number) {
  return new Date(new Date(base).getTime() + minutesAfter * 60_000).toISOString();
}

const fixtureNodes: OverviewSnapshot["nodes"] = [
  {
    id: "node1",
    name: "Foundry",
    ip: "192.168.1.244",
    role: "AI inference + agents",
    totalServices: 5,
    healthyServices: 4,
    degradedServices: 1,
    averageLatencyMs: 248,
    gpuUtilization: 74,
  },
  {
    id: "node2",
    name: "Workshop",
    ip: "192.168.1.225",
    role: "Creative + interface",
    totalServices: 3,
    healthyServices: 3,
    degradedServices: 0,
    averageLatencyMs: 189,
    gpuUtilization: 57,
  },
  {
    id: "vault",
    name: "VAULT",
    ip: "192.168.1.203",
    role: "Storage + media + monitoring",
    totalServices: 5,
    healthyServices: 5,
    degradedServices: 0,
    averageLatencyMs: 132,
    gpuUtilization: null,
  },
];

const fixtureServices: ServicesSnapshot["services"] = [
  {
    id: "litellm-proxy",
    name: "LiteLLM Proxy",
    nodeId: "vault",
    node: "VAULT",
    category: "inference",
    description: "Unified model routing and auth edge.",
    url: "http://192.168.1.203:4000/health/readiness",
    healthy: true,
    latencyMs: 82,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "node1-vllm",
    name: "vLLM (Node 1)",
    nodeId: "node1",
    node: "Foundry",
    category: "inference",
    description: "Primary large-model runtime.",
    url: "http://192.168.1.244:8000/v1/models",
    healthy: true,
    latencyMs: 364,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "node2-vllm",
    name: "vLLM (Node 2)",
    nodeId: "node2",
    node: "Workshop",
    category: "inference",
    description: "Secondary interactive runtime.",
    url: "http://192.168.1.225:8000/v1/models",
    healthy: true,
    latencyMs: 218,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "agent-server",
    name: "Agent Server",
    nodeId: "node1",
    node: "Foundry",
    category: "platform",
    description: "FastAPI runtime for Athanor agents.",
    url: "http://192.168.1.244:9000/health",
    healthy: true,
    latencyMs: 141,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "prometheus",
    name: "Prometheus",
    nodeId: "vault",
    node: "VAULT",
    category: "observability",
    description: "Metrics scrape and query surface.",
    url: "http://192.168.1.203:9090/-/healthy",
    healthy: true,
    latencyMs: 109,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "grafana",
    name: "Grafana",
    nodeId: "vault",
    node: "VAULT",
    category: "observability",
    description: "Dashboards and alert drill-down.",
    url: "http://192.168.1.203:3000/api/health",
    healthy: true,
    latencyMs: 154,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "open-webui",
    name: "Open WebUI",
    nodeId: "node2",
    node: "Workshop",
    category: "experience",
    description: "Experimental multi-model chat surface.",
    url: "http://192.168.1.225:3000",
    healthy: true,
    latencyMs: 207,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    nodeId: "node2",
    node: "Workshop",
    category: "experience",
    description: "Creative workflow engine.",
    url: "http://192.168.1.225:8188/system_stats",
    healthy: true,
    latencyMs: 146,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "speaches",
    name: "Speaches",
    nodeId: "node1",
    node: "Foundry",
    category: "platform",
    description: "Speech synthesis runtime.",
    url: "http://192.168.1.244:8200/health",
    healthy: false,
    latencyMs: null,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "degraded",
  },
  {
    id: "plex",
    name: "Plex",
    nodeId: "vault",
    node: "VAULT",
    category: "media",
    description: "Primary media serving platform.",
    url: "http://192.168.1.203:32400/identity",
    healthy: true,
    latencyMs: 192,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "sonarr",
    name: "Sonarr",
    nodeId: "vault",
    node: "VAULT",
    category: "media",
    description: "TV acquisition automation.",
    url: "http://192.168.1.203:8989/ping",
    healthy: true,
    latencyMs: 101,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "radarr",
    name: "Radarr",
    nodeId: "vault",
    node: "VAULT",
    category: "media",
    description: "Movie acquisition automation.",
    url: "http://192.168.1.203:7878/ping",
    healthy: true,
    latencyMs: 98,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
  {
    id: "stash",
    name: "Stash",
    nodeId: "vault",
    node: "VAULT",
    category: "media",
    description: "Media catalog and search runtime.",
    url: "http://192.168.1.203:9999",
    healthy: true,
    latencyMs: 173,
    checkedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 2),
    state: "healthy",
  },
];

const fixtureServiceAggregate: ServicesHistorySnapshot["aggregate"] = [
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 180), value: 91 },
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 150), value: 93 },
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 120), value: 95 },
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 90), value: 95 },
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 60), value: 97 },
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 30), value: 98 },
  { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 0), value: 92 },
];

const fixtureServiceSeries: ServicesHistorySnapshot["series"] = fixtureServices.map((service) => ({
  serviceId: service.id,
  serviceName: service.name,
  nodeId: service.nodeId,
  category: service.category,
  points: fixtureServiceAggregate.map((point, index) => ({
    timestamp: point.timestamp,
    availability:
      service.id === "speaches" && index >= fixtureServiceAggregate.length - 2
        ? 0
        : 1,
    latencyMs:
      service.latencyMs === null
        ? null
        : service.latencyMs + (index % 2 === 0 ? 12 : -8),
  })),
}));

const fixtureGpuSnapshot: GpuSnapshotResponse = {
  generatedAt: FIXTURE_BASE_TIME,
  summary: {
    gpuCount: 4,
    averageUtilization: 66.5,
    averageTemperature: 68.75,
    totalPowerW: 895,
    totalMemoryUsedMiB: 78464,
    totalMemoryMiB: 143360,
  },
  nodes: [
    {
      nodeId: "node1",
      node: "Foundry",
      gpuCount: 2,
      averageUtilization: 78,
      averageTemperature: 72.5,
      totalPowerW: 510,
      totalMemoryUsedMiB: 57344,
      totalMemoryMiB: 98304,
    },
    {
      nodeId: "node2",
      node: "Workshop",
      gpuCount: 2,
      averageUtilization: 55,
      averageTemperature: 65,
      totalPowerW: 385,
      totalMemoryUsedMiB: 21120,
      totalMemoryMiB: 45056,
    },
    {
      nodeId: "vault",
      node: "VAULT",
      gpuCount: 0,
      averageUtilization: null,
      averageTemperature: null,
      totalPowerW: null,
      totalMemoryUsedMiB: null,
      totalMemoryMiB: null,
    },
  ],
  gpus: [
    {
      id: "node1::00000000:01:00.0",
      gpuName: "RTX 4090",
      gpuBusId: "00000000:01:00.0",
      instance: "192.168.1.244:9400",
      nodeId: "node1",
      node: "Foundry",
      utilization: 92,
      memoryUsedMiB: 28672,
      memoryTotalMiB: 49152,
      temperatureC: 76,
      powerW: 288,
    },
    {
      id: "node1::00000000:02:00.0",
      gpuName: "RTX 4090",
      gpuBusId: "00000000:02:00.0",
      instance: "192.168.1.244:9400",
      nodeId: "node1",
      node: "Foundry",
      utilization: 64,
      memoryUsedMiB: 28672,
      memoryTotalMiB: 49152,
      temperatureC: 69,
      powerW: 222,
    },
    {
      id: "node2::00000000:01:00.0",
      gpuName: "RTX 3090",
      gpuBusId: "00000000:01:00.0",
      instance: "192.168.1.225:9400",
      nodeId: "node2",
      node: "Workshop",
      utilization: 58,
      memoryUsedMiB: 12288,
      memoryTotalMiB: 24576,
      temperatureC: 67,
      powerW: 198,
    },
    {
      id: "node2::00000000:02:00.0",
      gpuName: "RTX 3090",
      gpuBusId: "00000000:02:00.0",
      instance: "192.168.1.225:9400",
      nodeId: "node2",
      node: "Workshop",
      utilization: 52,
      memoryUsedMiB: 8832,
      memoryTotalMiB: 20480,
      temperatureC: 63,
      powerW: 187,
    },
  ],
};

const fixtureGpuHistory: GpuHistoryResponse = {
  generatedAt: FIXTURE_BASE_TIME,
  window: "3h",
  nodes: [
    {
      id: "node1",
      label: "Foundry",
      points: [
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 180), value: 68 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 150), value: 71 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 120), value: 74 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 90), value: 76 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 60), value: 79 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 30), value: 81 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 0), value: 78 },
      ],
    },
    {
      id: "node2",
      label: "Workshop",
      points: [
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 180), value: 42 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 150), value: 46 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 120), value: 53 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 90), value: 56 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 60), value: 57 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 30), value: 59 },
        { timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 0), value: 55 },
      ],
    },
  ],
  gpus: fixtureGpuSnapshot.gpus.map((gpu, gpuIndex) => ({
    id: gpu.id,
    label: gpu.gpuName,
    nodeId: gpu.nodeId,
    points: [
      180, 150, 120, 90, 60, 30, 0,
    ].map((minutesBefore, index) => ({
      timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, minutesBefore),
      utilization:
        (gpu.utilization ?? 0) -
        (gpuIndex % 2 === 0 ? 10 : 6) +
        index * (gpuIndex % 2 === 0 ? 2 : 1),
      temperatureC:
        (gpu.temperatureC ?? 0) - 4 + index,
      powerW:
        gpu.powerW === null ? null : gpu.powerW - 18 + index * 3,
      memoryRatio:
        gpu.memoryTotalMiB
          ? ((gpu.memoryUsedMiB ?? 0) / gpu.memoryTotalMiB) * 100
          : null,
    })),
  })),
};

const fixtureBackends: ModelsSnapshot["backends"] = [
  {
    id: "litellm-proxy",
    name: "LiteLLM Proxy",
    description: "Unified routing layer for direct inference and embeddings.",
    nodeId: "vault",
    url: "http://192.168.1.203:4000",
    reachable: true,
    modelCount: 3,
    models: ["/models/qwen3-32b", "/models/qwen3-14b", "/models/nomic-embed"],
  },
  {
    id: "node1-vllm",
    name: "Foundry / Qwen3-32B",
    description: "Primary large-model runtime.",
    nodeId: "node1",
    url: "http://192.168.1.244:8000",
    reachable: true,
    modelCount: 2,
    models: ["/models/qwen3-32b", "/models/deepseek-r1-distill"],
  },
  {
    id: "node2-vllm",
    name: "Workshop / Qwen3-14B",
    description: "Secondary runtime for interactive workloads.",
    nodeId: "node2",
    url: "http://192.168.1.225:8000",
    reachable: true,
    modelCount: 2,
    models: ["/models/qwen3-14b", "/models/phi-4-mini"],
  },
];

const fixtureModels: ModelsSnapshot = {
  generatedAt: FIXTURE_BASE_TIME,
  backends: fixtureBackends,
  models: [
    {
      id: "/models/qwen3-32b",
      backendId: "litellm-proxy",
      backend: "LiteLLM Proxy",
      target: "litellm-proxy",
      description: "High-capacity reasoning model.",
      available: true,
    },
    {
      id: "/models/qwen3-14b",
      backendId: "litellm-proxy",
      backend: "LiteLLM Proxy",
      target: "litellm-proxy",
      description: "Fast general assistant model.",
      available: true,
    },
    {
      id: "/models/nomic-embed",
      backendId: "litellm-proxy",
      backend: "LiteLLM Proxy",
      target: "litellm-proxy",
      description: "Embedding model for semantic search.",
      available: true,
    },
    {
      id: "/models/deepseek-r1-distill",
      backendId: "node1-vllm",
      backend: "Foundry / Qwen3-32B",
      target: "node1-vllm",
      description: "Local reasoning runtime.",
      available: true,
    },
    {
      id: "/models/phi-4-mini",
      backendId: "node2-vllm",
      backend: "Workshop / Qwen3-14B",
      target: "node2-vllm",
      description: "Smaller interactive model.",
      available: true,
    },
  ],
};

const fixtureAgents: AgentsSnapshot = {
  generatedAt: FIXTURE_BASE_TIME,
  agents: [
    {
      id: "general-assistant",
      name: "General Assistant",
      description: "Cross-stack research, operations, and writing support.",
      icon: "terminal",
      tools: ["cluster_health", "gpu_snapshot", "model_inventory"],
      status: "ready",
    },
    {
      id: "media-agent",
      name: "Media Agent",
      description: "Plex, stash, and media library support.",
      icon: "film",
      tools: ["plex_status", "stash_search", "recent_history"],
      status: "ready",
    },
    {
      id: "creative-agent",
      name: "Creative Agent",
      description: "Image and video generation across ComfyUI workflows.",
      icon: "sparkles",
      tools: ["generate_image", "generate_video", "queue_status"],
      status: "ready",
    },
    {
      id: "research-agent",
      name: "Research Agent",
      description: "Web research, synthesis, and retrieval-heavy discovery.",
      icon: "search",
      tools: ["web_search", "fetch_page", "search_knowledge"],
      status: "ready",
    },
    {
      id: "coding-agent",
      name: "Coding Agent",
      description: "Autonomous implementation and codebase operations.",
      icon: "code",
      tools: ["generate_code", "write_file", "run_command"],
      status: "ready",
    },
    {
      id: "knowledge-agent",
      name: "Knowledge Agent",
      description: "Documentation, ADR, and knowledge-base curation.",
      icon: "book-open",
      tools: ["search_knowledge", "list_documents", "graph_queries"],
      status: "ready",
    },
    {
      id: "home-agent",
      name: "Home Agent",
      description: "Home automation surface held in standby.",
      icon: "home",
      tools: ["lights", "scenes", "presence"],
      status: "unavailable",
    },
  ],
};

const fixtureWorkforce: WorkforceSnapshot = {
  generatedAt: FIXTURE_BASE_TIME,
  summary: {
    totalTasks: 8,
    pendingTasks: 2,
    pendingApprovals: 2,
    runningTasks: 1,
    completedTasks: 2,
    failedTasks: 1,
    activeGoals: 3,
    unreadNotifications: 1,
    avgTrustScore: 0.72,
    workspaceUtilization: 0.57,
    activeProjects: 3,
    queuedProjects: 3,
  },
  workplan: {
    current: {
      planId: "wp-1741531200",
      generatedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 48),
      timeContext: "Monday afternoon operator pass",
      focus: "Push EoBQ content and keep Athanor drift in check.",
      taskCount: 4,
      tasks: [
        {
          taskId: "task-eoq-1",
          agentId: "coding-agent",
          projectId: "eoq",
          prompt: "Implement the next EoBQ scene renderer state machine and branching transitions.",
          priority: "high",
          rationale: "Unblocks the playable narrative path for the first tenant milestone.",
          requiresApproval: true,
        },
        {
          taskId: "task-eoq-2",
          agentId: "creative-agent",
          projectId: "eoq",
          prompt: "Generate a portrait pack for the current dark-fantasy cast using the approved style lane.",
          priority: "normal",
          rationale: "Supports the active dialogue and scene work with fresh asset coverage.",
          requiresApproval: false,
        },
        {
          taskId: "task-ath-1",
          agentId: "research-agent",
          projectId: "athanor",
          prompt: "Audit the live LiteLLM alias map against docs and deployment outputs.",
          priority: "high",
          rationale: "Prevents contract drift in the operating environment while the roadmap lands.",
          requiresApproval: false,
        },
        {
          taskId: "task-ath-2",
          agentId: "knowledge-agent",
          projectId: "athanor",
          prompt: "Identify stale command-center docs and produce a delta list with missing operator guidance.",
          priority: "low",
          rationale: "Keeps the one-person operating model legible as the system expands.",
          requiresApproval: false,
        },
      ],
    },
    history: [
      {
        planId: "wp-1741531200",
        generatedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 48),
        timeContext: "Monday afternoon operator pass",
        focus: "Push EoBQ content and keep Athanor drift in check.",
        taskCount: 4,
        tasks: [
          {
            taskId: "task-eoq-1",
            agentId: "coding-agent",
            projectId: "eoq",
            prompt: "Implement the next EoBQ scene renderer state machine and branching transitions.",
            priority: "high",
            rationale: "Unblocks the playable narrative path for the first tenant milestone.",
            requiresApproval: true,
          },
          {
            taskId: "task-eoq-2",
            agentId: "creative-agent",
            projectId: "eoq",
            prompt: "Generate a portrait pack for the current dark-fantasy cast using the approved style lane.",
            priority: "normal",
            rationale: "Supports the active dialogue and scene work with fresh asset coverage.",
            requiresApproval: false,
          },
          {
            taskId: "task-ath-1",
            agentId: "research-agent",
            projectId: "athanor",
            prompt: "Audit the live LiteLLM alias map against docs and deployment outputs.",
            priority: "high",
            rationale: "Prevents contract drift in the operating environment while the roadmap lands.",
            requiresApproval: false,
          },
          {
            taskId: "task-ath-2",
            agentId: "knowledge-agent",
            projectId: "athanor",
            prompt: "Identify stale command-center docs and produce a delta list with missing operator guidance.",
            priority: "low",
            rationale: "Keeps the one-person operating model legible as the system expands.",
            requiresApproval: false,
          },
        ],
      },
      {
        planId: "wp-1741524000",
        generatedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 180),
        timeContext: "Morning planning run",
        focus: "Stabilize the cluster and refill the media lane.",
        taskCount: 3,
        tasks: [
          {
            taskId: "task-media-1",
            agentId: "media-agent",
            projectId: "media",
            prompt: "Review the current Sonarr and Radarr queues for stuck imports and stale downloads.",
            priority: "normal",
            rationale: "Maintains the media stack without adding low-value churn.",
            requiresApproval: false,
          },
          {
            taskId: "task-ath-0",
            agentId: "general-assistant",
            projectId: "athanor",
            prompt: "Summarize degraded services, GPU hotspots, and operator actions for the morning brief.",
            priority: "normal",
            rationale: "Provides a high-signal operating summary for the day.",
            requiresApproval: false,
          },
          {
            taskId: "task-kindred-1",
            agentId: "research-agent",
            projectId: "kindred",
            prompt: "Survey recent passion-based social products and note product patterns worth tracking.",
            priority: "low",
            rationale: "Keeps the scaffolded tenant warm without distracting from active builds.",
            requiresApproval: false,
          },
        ],
      },
    ],
    needsRefill: false,
    schedule: {
      morningRunHourLocal: 7,
      morningRunMinuteLocal: 0,
      refillIntervalHours: 2,
      minPendingTasks: 2,
      nextRunAt: isoMinutesAfter(FIXTURE_BASE_TIME, 96),
    },
  },
  tasks: [
    {
      id: "task-eoq-1",
      agentId: "coding-agent",
      prompt: "Implement the next EoBQ scene renderer state machine and branching transitions.",
      priority: "high",
      status: "pending_approval",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 47),
      startedAt: null,
      completedAt: null,
      durationMs: null,
      requiresApproval: true,
      source: "work_planner",
      projectId: "eoq",
      planId: "wp-1741531200",
      rationale: "Unblocks the playable narrative path for the first tenant milestone.",
      parentTaskId: null,
      result: null,
      error: null,
      stepCount: 0,
    },
    {
      id: "task-eoq-2",
      agentId: "creative-agent",
      prompt: "Generate a portrait pack for the current dark-fantasy cast using the approved style lane.",
      priority: "normal",
      status: "pending",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 46),
      startedAt: null,
      completedAt: null,
      durationMs: null,
      requiresApproval: false,
      source: "work_planner",
      projectId: "eoq",
      planId: "wp-1741531200",
      rationale: "Supports the active dialogue and scene work with fresh asset coverage.",
      parentTaskId: null,
      result: null,
      error: null,
      stepCount: 0,
    },
    {
      id: "task-ath-1",
      agentId: "research-agent",
      prompt: "Audit the live LiteLLM alias map against docs and deployment outputs.",
      priority: "high",
      status: "running",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 44),
      startedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 34),
      completedAt: null,
      durationMs: null,
      requiresApproval: false,
      source: "work_planner",
      projectId: "athanor",
      planId: "wp-1741531200",
      rationale: "Prevents contract drift in the operating environment while the roadmap lands.",
      parentTaskId: null,
      result: null,
      error: null,
      stepCount: 5,
    },
    {
      id: "task-ath-2",
      agentId: "knowledge-agent",
      prompt: "Identify stale command-center docs and produce a delta list with missing operator guidance.",
      priority: "low",
      status: "pending",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 43),
      startedAt: null,
      completedAt: null,
      durationMs: null,
      requiresApproval: false,
      source: "work_planner",
      projectId: "athanor",
      planId: "wp-1741531200",
      rationale: "Keeps the one-person operating model legible as the system expands.",
      parentTaskId: null,
      result: null,
      error: null,
      stepCount: 0,
    },
    {
      id: "task-home-1",
      agentId: "home-agent",
      prompt: "Adjust the evening lighting automation after the recent occupancy drift report.",
      priority: "high",
      status: "pending_approval",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 21),
      startedAt: null,
      completedAt: null,
      durationMs: null,
      requiresApproval: true,
      source: "manual",
      projectId: "athanor",
      planId: null,
      rationale: null,
      parentTaskId: null,
      result: null,
      error: null,
      stepCount: 0,
    },
    {
      id: "task-ath-brief",
      agentId: "general-assistant",
      prompt: "Summarize degraded services, GPU hotspots, and operator actions for the morning brief.",
      priority: "normal",
      status: "completed",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 190),
      startedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 188),
      completedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 183),
      durationMs: 300000,
      requiresApproval: false,
      source: "work_planner",
      projectId: "athanor",
      planId: "wp-1741524000",
      rationale: "Provides a high-signal operating summary for the day.",
      parentTaskId: null,
      result: "Morning brief published with service drift, GPU hotspot, and queue notes.",
      error: null,
      stepCount: 4,
    },
    {
      id: "task-kindred-1",
      agentId: "research-agent",
      prompt: "Survey recent passion-based social products and note product patterns worth tracking.",
      priority: "low",
      status: "completed",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 170),
      startedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 165),
      completedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 149),
      durationMs: 960000,
      requiresApproval: false,
      source: "work_planner",
      projectId: "kindred",
      planId: "wp-1741524000",
      rationale: "Keeps the scaffolded tenant warm without distracting from active builds.",
      parentTaskId: null,
      result: "Research memo recorded with three adjacent product patterns and open questions.",
      error: null,
      stepCount: 6,
    },
    {
      id: "task-media-1",
      agentId: "media-agent",
      prompt: "Review the current Sonarr and Radarr queues for stuck imports and stale downloads.",
      priority: "normal",
      status: "failed",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 150),
      startedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 144),
      completedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 138),
      durationMs: 360000,
      requiresApproval: false,
      source: "work_planner",
      projectId: "media",
      planId: "wp-1741524000",
      rationale: "Maintains the media stack without adding low-value churn.",
      parentTaskId: null,
      result: null,
      error: "Sonarr queue returned a transient upstream timeout during queue hydration.",
      stepCount: 3,
    },
  ],
  goals: [
    {
      id: "goal-ops-1",
      text: "Keep Athanor coherent as a one-person operating environment, not a bag of tools.",
      agentId: "global",
      priority: "high",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 260),
      active: true,
    },
    {
      id: "goal-eoq-1",
      text: "Prioritize EoBQ tenant momentum when tradeoffs compete with internal polish work.",
      agentId: "global",
      priority: "high",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 240),
      active: true,
    },
    {
      id: "goal-docs-1",
      text: "Keep operator-facing docs aligned with current deployment contracts and project posture.",
      agentId: "knowledge-agent",
      priority: "normal",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 220),
      active: true,
    },
  ],
  trust: [
    {
      agentId: "general-assistant",
      trustScore: 0.81,
      trustGrade: "A",
      positiveFeedback: 23,
      negativeFeedback: 2,
      totalFeedback: 25,
      escalationCount: 1,
    },
    {
      agentId: "media-agent",
      trustScore: 0.76,
      trustGrade: "B",
      positiveFeedback: 16,
      negativeFeedback: 3,
      totalFeedback: 19,
      escalationCount: 2,
    },
    {
      agentId: "creative-agent",
      trustScore: 0.74,
      trustGrade: "B",
      positiveFeedback: 13,
      negativeFeedback: 4,
      totalFeedback: 17,
      escalationCount: 2,
    },
    {
      agentId: "research-agent",
      trustScore: 0.72,
      trustGrade: "B",
      positiveFeedback: 18,
      negativeFeedback: 5,
      totalFeedback: 23,
      escalationCount: 3,
    },
    {
      agentId: "coding-agent",
      trustScore: 0.68,
      trustGrade: "B",
      positiveFeedback: 14,
      negativeFeedback: 5,
      totalFeedback: 19,
      escalationCount: 4,
    },
    {
      agentId: "knowledge-agent",
      trustScore: 0.63,
      trustGrade: "B",
      positiveFeedback: 9,
      negativeFeedback: 4,
      totalFeedback: 13,
      escalationCount: 2,
    },
    {
      agentId: "home-agent",
      trustScore: 0.51,
      trustGrade: "C",
      positiveFeedback: 3,
      negativeFeedback: 3,
      totalFeedback: 6,
      escalationCount: 5,
    },
  ],
  notifications: [
    {
      id: "notif-home-1",
      agentId: "home-agent",
      action: "Adjust evening lighting automation",
      category: "routine",
      confidence: 0.41,
      description: "The home lane wants approval before changing the current presence-based lighting automation.",
      tier: "ask",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 20),
      resolved: false,
      resolution: null,
    },
    {
      id: "notif-media-1",
      agentId: "media-agent",
      action: "Queued a notice about a transient Sonarr import stall",
      category: "content",
      confidence: 0.83,
      description: "The media lane auto-acted and logged the failure for later review.",
      tier: "notify",
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 130),
      resolved: true,
      resolution: "approved",
    },
  ],
  workspace: {
    totalItems: 4,
    broadcastItems: 4,
    capacity: 7,
    utilization: 4 / 7,
    competitionRunning: true,
    agentsActive: [
      { agentId: "research-agent", count: 1 },
      { agentId: "general-assistant", count: 1 },
      { agentId: "media-agent", count: 1 },
      { agentId: "knowledge-agent", count: 1 },
    ],
    topItem: {
      id: "ws-ops-1",
      sourceAgent: "general-assistant",
      content: "Forge failures point to a missing 4x-UltraSharp upscaler dependency in the current image lane.",
      priority: "high",
      salience: 4.6,
      createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 8),
      ttlSeconds: 300,
      coalition: ["creative-agent", "coding-agent"],
      projectId: "athanor",
    },
    broadcast: [
      {
        id: "ws-ops-1",
        sourceAgent: "general-assistant",
        content: "Forge failures point to a missing 4x-UltraSharp upscaler dependency in the current image lane.",
        priority: "high",
        salience: 4.6,
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 8),
        ttlSeconds: 300,
        coalition: ["creative-agent", "coding-agent"],
        projectId: "athanor",
      },
      {
        id: "ws-eoq-1",
        sourceAgent: "creative-agent",
        content: "EoBQ portrait generation is blocked on fresh prompt cards for the current cast.",
        priority: "normal",
        salience: 2.8,
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 11),
        ttlSeconds: 300,
        coalition: ["coding-agent"],
        projectId: "eoq",
      },
      {
        id: "ws-media-1",
        sourceAgent: "media-agent",
        content: "Sonarr queue recovered after timeout, but one import is still worth manual verification.",
        priority: "normal",
        salience: 2.1,
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 17),
        ttlSeconds: 300,
        coalition: [],
        projectId: "media",
      },
      {
        id: "ws-kindred-1",
        sourceAgent: "research-agent",
        content: "Kindred research found adjacent products but nothing with strong passion-first onboarding yet.",
        priority: "low",
        salience: 0.9,
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 23),
        ttlSeconds: 300,
        coalition: [],
        projectId: "kindred",
      },
    ],
  },
  subscriptions: [
    {
      agentId: "media-agent",
      keywords: ["sonarr", "radarr", "plex", "import", "queue"],
      sourceFilters: ["event:media", "service:plex"],
      threshold: 0.35,
      reactPromptTemplate: "Handle media-domain signal: {content}",
    },
    {
      agentId: "creative-agent",
      keywords: ["forge", "comfyui", "render", "upscaler", "image"],
      sourceFilters: ["event:creative", "project:eoq"],
      threshold: 0.42,
      reactPromptTemplate: "Investigate creative pipeline issue: {content}",
    },
    {
      agentId: "knowledge-agent",
      keywords: ["docs", "adr", "contract", "manifest", "roadmap"],
      sourceFilters: ["project:athanor", "workspace"],
      threshold: 0.28,
      reactPromptTemplate: "Capture and reconcile this operating knowledge: {content}",
    },
  ],
  conventions: {
    proposed: [
      {
        id: "conv-proposed-1",
        type: "quality",
        agentId: "coding-agent",
        description: "Route all operator-facing dashboard changes through typed dashboard-owned APIs before UI adoption.",
        rule: "No new production UI page should call node services directly from the browser.",
        source: "dashboard migration",
        occurrences: 4,
        status: "proposed",
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 55),
        confirmedAt: null,
      },
    ],
    confirmed: [
      {
        id: "conv-confirmed-1",
        type: "behavior",
        agentId: "general-assistant",
        description: "Prefer Command Center visibility for high-signal cluster or workforce changes.",
        rule: "Escalate meaningful system drift into the workspace and operator dashboard surfaces.",
        source: "operator review",
        occurrences: 12,
        status: "confirmed",
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 720),
        confirmedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 690),
      },
      {
        id: "conv-confirmed-2",
        type: "preference",
        agentId: "knowledge-agent",
        description: "Treat BUILD-MANIFEST as the tactical queue under the Athanor Next roadmap.",
        rule: "Roadmap defines direction; manifest defines execution sequence.",
        source: "docs convergence",
        occurrences: 6,
        status: "confirmed",
        createdAt: isoMinutesBefore(FIXTURE_BASE_TIME, 640),
        confirmedAt: isoMinutesBefore(FIXTURE_BASE_TIME, 600),
      },
    ],
  },
  improvement: {
    totalProposals: 18,
    pending: 3,
    validated: 6,
    deployed: 7,
    failed: 2,
    benchmarkResults: 41,
    lastCycle: {
      timestamp: isoMinutesBefore(FIXTURE_BASE_TIME, 95),
      patternsConsumed: 11,
      proposalsGenerated: 4,
      benchmarks: {
        passed: 7,
        total: 8,
        passRate: 0.875,
      },
    },
  },
  agents: [
    {
      id: "general-assistant",
      name: "General Assistant",
      description: "Cross-stack research, operations, and writing support.",
      icon: "terminal",
      type: "proactive",
      status: "ready",
      tools: ["cluster_health", "gpu_snapshot", "model_inventory"],
      totalTasks: 1,
      runningTasks: 0,
      pendingTasks: 0,
      trustScore: 0.81,
      trustGrade: "A",
    },
    {
      id: "media-agent",
      name: "Media Agent",
      description: "Plex, stash, and media library support.",
      icon: "film",
      type: "proactive",
      status: "ready",
      tools: ["plex_status", "stash_search", "recent_history"],
      totalTasks: 1,
      runningTasks: 0,
      pendingTasks: 0,
      trustScore: 0.76,
      trustGrade: "B",
    },
    {
      id: "creative-agent",
      name: "Creative Agent",
      description: "Image and video generation across ComfyUI workflows.",
      icon: "sparkles",
      type: "reactive",
      status: "ready",
      tools: ["generate_image", "generate_video", "queue_status"],
      totalTasks: 1,
      runningTasks: 0,
      pendingTasks: 1,
      trustScore: 0.74,
      trustGrade: "B",
    },
    {
      id: "research-agent",
      name: "Research Agent",
      description: "Web research, synthesis, and retrieval-heavy discovery.",
      icon: "search",
      type: "reactive",
      status: "ready",
      tools: ["web_search", "fetch_page", "search_knowledge"],
      totalTasks: 2,
      runningTasks: 1,
      pendingTasks: 0,
      trustScore: 0.72,
      trustGrade: "B",
    },
    {
      id: "coding-agent",
      name: "Coding Agent",
      description: "Autonomous implementation and codebase operations.",
      icon: "code",
      type: "proactive",
      status: "ready",
      tools: ["generate_code", "write_file", "run_command"],
      totalTasks: 1,
      runningTasks: 0,
      pendingTasks: 0,
      trustScore: 0.68,
      trustGrade: "B",
    },
    {
      id: "knowledge-agent",
      name: "Knowledge Agent",
      description: "Documentation, ADR, and knowledge-base curation.",
      icon: "book-open",
      type: "reactive",
      status: "ready",
      tools: ["search_knowledge", "list_documents", "graph_queries"],
      totalTasks: 1,
      runningTasks: 0,
      pendingTasks: 1,
      trustScore: 0.63,
      trustGrade: "B",
    },
    {
      id: "home-agent",
      name: "Home Agent",
      description: "Home automation surface held in standby.",
      icon: "home",
      type: "proactive",
      status: "unavailable",
      tools: ["lights", "scenes", "presence"],
      totalTasks: 1,
      runningTasks: 0,
      pendingTasks: 0,
      trustScore: 0.51,
      trustGrade: "C",
    },
  ],
  projects: [
    {
      id: "athanor",
      name: "Athanor",
      status: "active",
      firstClass: true,
      lens: "system",
      primaryRoute: "/",
      externalUrl: null,
      needsCount: 3,
      mappedAgents: 3,
      totalTasks: 4,
      pendingTasks: 1,
      pendingApprovals: 1,
      runningTasks: 1,
      completedTasks: 1,
      failedTasks: 0,
      plannedTasks: 2,
      operatorChain: ["Shaun", "Claude"],
      topAgents: ["research-agent", "knowledge-agent", "general-assistant"],
    },
    {
      id: "eoq",
      name: "Empire of Broken Queens",
      status: "active",
      firstClass: true,
      lens: "eoq",
      primaryRoute: "/workplanner?project=eoq",
      externalUrl: "http://192.168.1.225:3002",
      needsCount: 5,
      mappedAgents: 3,
      totalTasks: 2,
      pendingTasks: 1,
      pendingApprovals: 1,
      runningTasks: 0,
      completedTasks: 0,
      failedTasks: 0,
      plannedTasks: 2,
      operatorChain: ["Claude", "creative-agent", "coding-agent"],
      topAgents: ["coding-agent", "creative-agent"],
    },
    {
      id: "kindred",
      name: "Kindred",
      status: "scaffolded",
      firstClass: false,
      lens: "default",
      primaryRoute: "/workplanner?project=kindred",
      externalUrl: null,
      needsCount: 1,
      mappedAgents: 1,
      totalTasks: 1,
      pendingTasks: 0,
      pendingApprovals: 0,
      runningTasks: 0,
      completedTasks: 1,
      failedTasks: 0,
      plannedTasks: 0,
      operatorChain: ["Claude", "research-agent"],
      topAgents: ["research-agent"],
    },
    {
      id: "media",
      name: "Media Library",
      status: "operational",
      firstClass: false,
      lens: "media",
      primaryRoute: "/media",
      externalUrl: "http://192.168.1.203:32400/web",
      needsCount: 2,
      mappedAgents: 1,
      totalTasks: 1,
      pendingTasks: 0,
      pendingApprovals: 0,
      runningTasks: 0,
      completedTasks: 0,
      failedTasks: 1,
      plannedTasks: 0,
      operatorChain: ["media-agent"],
      topAgents: ["media-agent"],
    },
  ],
  schedules: [
    {
      agentId: "media-agent",
      intervalSeconds: 900,
      intervalHuman: "every 15 min",
      enabled: true,
      lastRunAt: isoMinutesBefore(FIXTURE_BASE_TIME, 12),
      nextRunInSeconds: 180,
      priority: "normal",
    },
    {
      agentId: "home-agent",
      intervalSeconds: 300,
      intervalHuman: "every 5 min",
      enabled: true,
      lastRunAt: isoMinutesBefore(FIXTURE_BASE_TIME, 4),
      nextRunInSeconds: 60,
      priority: "high",
    },
    {
      agentId: "data-curator",
      intervalSeconds: 21600,
      intervalHuman: "every 6 hours",
      enabled: true,
      lastRunAt: isoMinutesBefore(FIXTURE_BASE_TIME, 100),
      nextRunInSeconds: 8400,
      priority: "low",
    },
  ],
};

const fixtureOverview: OverviewSnapshot = {
  generatedAt: FIXTURE_BASE_TIME,
  summary: {
    totalServices: fixtureServices.length,
    healthyServices: fixtureServices.filter((service) => service.healthy).length,
    degradedServices: fixtureServices.filter((service) => !service.healthy).length,
    averageLatencyMs: 165,
    averageGpuUtilization: fixtureGpuSnapshot.summary.averageUtilization,
    readyAgents: fixtureAgents.agents.filter((agent) => agent.status === "ready").length,
    totalAgents: fixtureAgents.agents.length,
    reachableBackends: fixtureBackends.filter((backend) => backend.reachable).length,
    totalBackends: fixtureBackends.length,
    activeProjects: 3,
    firstClassProjects: 2,
  },
  nodes: fixtureNodes,
  services: fixtureServices,
  serviceTrend: fixtureServiceAggregate,
  gpuTrend: fixtureGpuHistory.nodes[0].points.map((point, index) => ({
    timestamp: point.timestamp,
    value: Math.round(
      (((fixtureGpuHistory.nodes[0].points[index]?.value ?? 0) +
        (fixtureGpuHistory.nodes[1].points[index]?.value ?? 0)) /
        2) *
        10
    ) / 10,
  })),
  backends: fixtureBackends,
  agents: fixtureAgents.agents,
  projects: [
    {
      id: "athanor",
      name: "Athanor",
      description: "Core operating environment for the homelab and workforce.",
      headline: "Core operating environment for system state, workforce orchestration, and operator judgment.",
      status: "active",
      kind: "core",
      firstClass: true,
      lens: "system",
      primaryRoute: "/",
      externalUrl: null,
      agents: ["general-assistant", "coding-agent", "knowledge-agent"],
      needsCount: 3,
      constraints: ["One-person maintainable", "No busywork"],
      operatorChain: ["Shaun", "Claude"],
    },
    {
      id: "eoq",
      name: "Empire of Broken Queens",
      description: "AI-driven cinematic tenant app.",
      headline: "First first-class tenant for creative generation, dialogue, and cinematic interaction.",
      status: "active",
      kind: "tenant",
      firstClass: true,
      lens: "eoq",
      primaryRoute: "/workplanner?project=eoq",
      externalUrl: "http://192.168.1.225:3002",
      agents: ["creative-agent", "coding-agent", "research-agent"],
      needsCount: 5,
      constraints: ["Adult content intentional", "Dark fantasy aesthetic"],
      operatorChain: ["Claude", "creative-agent", "coding-agent"],
    },
    {
      id: "kindred",
      name: "Kindred",
      description: "Scaffolded future tenant in research mode.",
      headline: "Scaffolded future tenant in concept and research mode.",
      status: "scaffolded",
      kind: "scaffold",
      firstClass: false,
      lens: "default",
      primaryRoute: "/workplanner?project=kindred",
      externalUrl: null,
      agents: ["research-agent"],
      needsCount: 1,
      constraints: ["Research only"],
      operatorChain: ["Claude", "research-agent"],
    },
    {
      id: "media",
      name: "Media Library",
      description: "Operational media domain project.",
      headline: "Operational domain project spanning curation, acquisition, and catalog quality.",
      status: "operational",
      kind: "domain",
      firstClass: false,
      lens: "media",
      primaryRoute: "/media",
      externalUrl: "http://192.168.1.203:32400/web",
      agents: ["media-agent"],
      needsCount: 2,
      constraints: ["Quality over quantity"],
      operatorChain: ["media-agent"],
    },
  ],
  alerts: [
    {
      id: "speaches-outage",
      title: "Speaches is degraded",
      description: "Speech synthesis is unreachable from the latest dashboard probe.",
      tone: "degraded",
      href: "/services?service=speaches",
    },
    {
      id: "gpu-hotspot",
      title: "RTX 4090 hotspot on Foundry",
      description: "One card is sitting above 90% utilization and 76C.",
      tone: "warning",
      href: "/gpu?highlight=node1%3A%3A00000000%3A01%3A00.0",
    },
  ],
  hotspots: fixtureGpuSnapshot.gpus.slice(0, 4),
  externalTools: [
    {
      id: "grafana",
      label: "Grafana",
      description: "Dashboards, alerts, and metrics drill-downs.",
      url: "http://192.168.1.203:3000",
    },
    {
      id: "prometheus",
      label: "Prometheus",
      description: "Raw PromQL and scrape-state inspection.",
      url: "http://192.168.1.203:9090",
    },
    {
      id: "comfyui",
      label: "ComfyUI",
      description: "Creative workflows and queue triage.",
      url: "http://192.168.1.225:8188",
    },
    {
      id: "plex",
      label: "Plex",
      description: "Media library and playback control.",
      url: "http://192.168.1.203:32400/web",
    },
  ],
  workforce: fixtureWorkforce,
};

const fixtureServicesSnapshot: ServicesSnapshot = {
  generatedAt: FIXTURE_BASE_TIME,
  summary: {
    total: fixtureServices.length,
    healthy: fixtureServices.filter((service) => service.healthy).length,
    degraded: fixtureServices.filter((service) => !service.healthy).length,
    averageLatencyMs: 165,
    slowestServiceId: "node1-vllm",
    slowestServiceName: "vLLM (Node 1)",
  },
  nodes: fixtureNodes,
  services: fixtureServices,
};

const fixtureServicesHistory: ServicesHistorySnapshot = {
  generatedAt: FIXTURE_BASE_TIME,
  window: "3h",
  aggregate: fixtureServiceAggregate,
  series: fixtureServiceSeries,
};

export function isDashboardFixtureMode() {
  return process.env.DASHBOARD_FIXTURE_MODE === "1";
}

export function getFixtureOverviewSnapshot(): OverviewSnapshot {
  return cloneFixture(fixtureOverview);
}

export function getFixtureWorkforceSnapshot(): WorkforceSnapshot {
  return cloneFixture(fixtureWorkforce);
}

export function getFixtureServicesSnapshot(): ServicesSnapshot {
  return cloneFixture(fixtureServicesSnapshot);
}

export function getFixtureServicesHistory(window: string): ServicesHistorySnapshot {
  const next = cloneFixture(fixtureServicesHistory);
  next.window = window;
  return next;
}

export function getFixtureGpuSnapshot(): GpuSnapshotResponse {
  return cloneFixture(fixtureGpuSnapshot);
}

export function getFixtureGpuHistory(window: string): GpuHistoryResponse {
  const next = cloneFixture(fixtureGpuHistory);
  next.window = window;
  return next;
}

export function getFixtureModelsSnapshot(): ModelsSnapshot {
  return cloneFixture(fixtureModels);
}

export function getFixtureAgentsSnapshot(): AgentsSnapshot {
  return cloneFixture(fixtureAgents);
}
