export const queryKeys = {
  overview: ["overview"] as const,
  builderSummary: ["builder-summary"] as const,
  builderSession: (sessionId: string) => ["builder-session", sessionId] as const,
  builderSessionEvents: (sessionId: string) => ["builder-session-events", sessionId] as const,
  workforce: ["workforce"] as const,
  services: ["services"] as const,
  servicesHistory: (window: string) => ["services-history", window] as const,
  gpuSnapshot: ["gpu-snapshot"] as const,
  gpuHistory: (window: string) => ["gpu-history", window] as const,
  models: ["models"] as const,
  modelGovernance: ["models-governance"] as const,
  governor: ["governor"] as const,
  operationsReadiness: ["operations-readiness"] as const,
  operatorSummary: ["operator-summary"] as const,
  bootstrapPrograms: ["bootstrap-programs"] as const,
  judgePlane: (limit: number) => ["judge-plane", limit] as const,
  executionRuns: (limit: number) => ["execution-runs", limit] as const,
  scheduledJobs: (limit: number) => ["scheduled-jobs", limit] as const,
  agents: ["agents"] as const,
  systemMap: ["system-map"] as const,
  history: ["history"] as const,
  intelligence: ["intelligence"] as const,
  review: ["review"] as const,
  memory: ["memory"] as const,
  monitoring: ["monitoring"] as const,
  mediaOverview: ["media-overview"] as const,
  galleryOverview: ["gallery-overview"] as const,
  homeOverview: ["home-overview"] as const,
};
